WEBDRIVER_LOCALHOST = 'http://localhost:4723/wd/hub'

APP_PACKAGE = 'com.example.randommovie'
APP_ACTIVITY = 'com.example.randommovie.activities.MainTapeActivity'

LOGIN_BUTTON_NAME = 'login_button_log_in'
LOGIN_EMAIL = 'test@mail.ru'
LOGIN_PASSWORD = 'Test0001'
LOGIN_EMAIL_TEXT_FIELD = 'email_log_in'
LOGIN_PASS_TEXT_FIELD = 'password_log_in'
LOGIN_ASSERT_TEXT = ''

MAIN_MENU_TOP_BAR = '/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.LinearLayout[1]/android.view.ViewGroup/android.widget.TextView'
MOVIE_TITLE = 'movie_title'
MAIN_BAR = 'RandomMovie'
REGISTER_BUTTON_NAME = 'registration_sign_up'
REGISTER_EMAIL = 'test@mail.ru'
REGISTER_PASSWORD = 'Test0001'
REGISTER_USERNAME = 'test'
REGISTER_USERNAME_TEXT_FIELD = 'username_sign_up'
REGISTER_PASS_TEXT_FIELD = 'password_sign_up'
REGISTER_PASS_REP_TEXT_FIELD = 'repeat_password_sign_up'
REGISTER_EMAIL_TEXT_FIELD = 'email_sign_up'
REGISTER_ASSERT_TEXT = ''

PROFILE_BUTTON = 'profile'
PROFILE_MAIL = 'profile_data_email'
PROFILE_USERNAME = 'profile_data_login'
PROFILE_UPDATE_BUTTON = 'profile_data_update_button'

PROFILE_MENU_PROFILE = '/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout/androidx.recyclerview.widget.RecyclerView/androidx.appcompat.widget.LinearLayoutCompat[1]/android.widget.CheckedTextView'
PROFILE_MENU_BOOK = '/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout/androidx.recyclerview.widget.RecyclerView/androidx.appcompat.widget.LinearLayoutCompat[2]/android.widget.CheckedTextView'
PROFILE_MENU_FAV = '/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout/androidx.recyclerview.widget.RecyclerView/androidx.appcompat.widget.LinearLayoutCompat[3]/android.widget.CheckedTextView'
PROFILE_MENU_EXIT = ''
